version: "3.8"

services:
  postgress:
    image: postgres:15
    container_name: bioms_postgres
    environment:
      POSTGRES_USER: biomsdev
      POSTGRES_PASSWORD: bioms2024
      POSTGRES_DB: bioms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bioms_postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://biomsdev:bioms2024@85432:5432/bioms
    depends_on:
      - postgres

volumes:
  postgres_data:
